---
- hosts: servers
  become: true
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_type: plus
    nginx_rest_api_enable: true
    nginx_rest_api_port: 4321
    nginx_rest_api_write: true
    nginx_license:
      certificate: "/etc/ssl/nginx/nginx-repo.crt"
      key: "/etc/ssl/nginx/nginx-repo.key"
    nginx_modules:
      - njs

- hosts: servers
  become: true
  vars_files:
    - ~/ansible/vars/controller.yaml

  tasks:

    - name: Install required packages
      apt:
        name:
          - python2.7
        state: latest

    - name: retrieve the controller installer from the NGINX Controller
      get_url:
        dest: /tmp/install.sh
        mode: 0750
        url: https://{{ controller.hostname }}:8443/1.4/install/controller/
        validate_certs: no

    - name: Install the controller agent
      shell:
        cmd: "API_KEY='{{ controller.api_key }}' sh /tmp/install.sh -y"
        creates: /lib/systemd/system/controller-agent.service

