---
- hosts: k8s1
  become: true
  tasks:

  - name: Create the K8s PKI directory
    file:
      state: directory
      path: "/etc/kubernetes/pki"
      owner: "ubuntu"
      group: "ubuntu"
      mode: 0775

  - name: Copy the CA cert to the PKI folder
    copy:
      src: /home/ubuntu/CA/ca.cert.pem
      dest: /etc/kubernetes/pki/ca.crt

  - name: Copy the CA key to the PKI folder
    copy:
      src: /home/ubuntu/CA/ca.key.pem
      dest: /etc/kubernetes/pki/ca.key

  - name: Initialize the Kubernetes cluster using kubeadm
    command: 
      cmd: kubeadm init --apiserver-advertise-address="{{ ansible_default_ipv4.address }}" --apiserver-cert-extra-sans="{{ ansible_default_ipv4.address }}"  --node-name k8s1.{{ wsid }}.{{ domain }} --pod-network-cidr=192.168.0.0/16
      creates: /etc/kubernetes/admin.conf

  - name: Setup kubeconfig for ubuntu user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/ubuntu/.kube
     - cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
     - chown ubuntu:ubuntu /home/ubuntu/.kube/config

  - name: Install Weave pod network
    become: false
    shell:
      cmd: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

  - name: Generate join command
    command: kubeadm token create --print-join-command
    become: false
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="/home/ubuntu/k8s-join-command"

