---
- hosts: 
  - k8s2
  - k8s3
  - k8s4
  become: true
  tasks:

  - name: Copy the join command to server location
    copy:
      src: /home/ubuntu/k8s-join-command
      dest: /tmp/join-command.sh
      mode: 0700

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

