# Ansible variable configuration
---

cicd:
  git:
    hostname: cicd.multipass.test
    admin_username: nginx
    admin_password: "{{ lookup('password', '~/git.passwd length=12') }}"
    deploy_repos: no


  jenkins:
    # pkg.jenkins.io is slow. See: http://mirrors.jenkins-ci.org/status.html
    updates_url: http://mirror.serverion.com/jenkins/updates/
    hostname: cicd.multipass.test
    http_port: 8080
    url_prefix: /
    proxy_url: https://jenkins.mboddington.nginx/
    admin_username: nginx
    admin_password: "{{ lookup('password', '~/jenkins.passwd length=12') }}"

  docker:
    secure: true
    home: /home/docker
    admin_username: nginx
    admin_password: "{{ lookup('password', '~/secrets/docker.cicd.passwd length=12') }}"

